"""
constants.py — HIFZ TRACKER 2.0
Quran metadata (Surahs, Ayahs, Juz mapping).
Extracted to a shared backend module for strict validation logic.
"""

SURAH_LIST = [
    "Al-Fatihah","Al-Baqarah","Al-Imran","An-Nisa","Al-Ma'idah",
    "Al-An'am","Al-A'raf","Al-Anfal","At-Tawbah","Yunus",
    "Hud","Yusuf","Ar-Ra'd","Ibrahim","Al-Hijr",
    "An-Nahl","Al-Isra","Al-Kahf","Maryam","Ta-Ha",
    "Al-Anbiya","Al-Hajj","Al-Mu'minun","An-Nur","Al-Furqan",
    "Ash-Shu'ara","An-Naml","Al-Qasas","Al-Ankabut","Ar-Rum",
    "Luqman","As-Sajdah","Al-Ahzab","Saba","Fatir",
    "Ya-Sin","As-Saffat","Sad","Az-Zumar","Ghafir",
    "Fussilat","Ash-Shura","Az-Zukhruf","Ad-Dukhan","Al-Jathiyah",
    "Al-Ahqaf","Muhammad","Al-Fath","Al-Hujurat","Qaf",
    "Adh-Dhariyat","At-Tur","An-Najm","Al-Qamar","Ar-Rahman",
    "Al-Waqi'ah","Al-Hadid","Al-Mujadila","Al-Hashr","Al-Mumtahanah",
    "As-Saf","Al-Jumu'ah","Al-Munafiqun","At-Taghabun","At-Talaq",
    "At-Tahrim","Al-Mulk","Al-Qalam","Al-Haqqah","Al-Ma'arij",
    "Nuh","Al-Jinn","Al-Muzzammil","Al-Muddaththir","Al-Qiyamah",
    "Al-Insan","Al-Mursalat","An-Naba","An-Nazi'at","Abasa",
    "At-Takwir","Al-Infitar","Al-Mutaffifin","Al-Inshiqaq","Al-Buruj",
    "At-Tariq","Al-A'la","Al-Ghashiyah","Al-Fajr","Al-Balad",
    "Ash-Shams","Al-Layl","Ad-Duha","Ash-Sharh","At-Tin",
    "Al-Alaq","Al-Qadr","Al-Bayyinah","Az-Zalzalah","Al-Adiyat",
    "Al-Qari'ah","At-Takathur","Al-Asr","Al-Humazah","Al-Fil",
    "Quraysh","Al-Ma'un","Al-Kawthar","Al-Kafirun","An-Nasr",
    "Al-Masad","Al-Ikhlas","Al-Falaq","An-Nas"
]

# Create a mapping for ordering
SURAH_ORDER = {name: index for index, name in enumerate(SURAH_LIST)}

JUZ_SURAHS = {
    1: ["Al-Fatihah", "Al-Baqarah"],
    2: ["Al-Baqarah"],
    3: ["Al-Baqarah", "Al-Imran"],
    4: ["Al-Imran", "An-Nisa"],
    5: ["An-Nisa"],
    6: ["An-Nisa", "Al-Ma'idah"],
    7: ["Al-Ma'idah", "Al-An'am"],
    8: ["Al-An'am", "Al-A'raf"],
    9: ["Al-A'raf", "Al-Anfal"],
    10: ["Al-Anfal", "At-Tawbah"],
    11: ["At-Tawbah", "Yunus", "Hud"],
    12: ["Hud", "Yusuf"],
    13: ["Yusuf", "Ar-Ra'd", "Ibrahim"],
    14: ["Al-Hijr", "An-Nahl"],
    15: ["Al-Isra", "Al-Kahf"],
    16: ["Al-Kahf", "Maryam", "Ta-Ha"],
    17: ["Al-Anbiya", "Al-Hajj"],
    18: ["Al-Mu'minun", "An-Nur", "Al-Furqan"],
    19: ["Al-Furqan", "Ash-Shu'ara", "An-Naml"],
    20: ["An-Naml", "Al-Qasas", "Al-Ankabut"],
    21: ["Al-Ankabut", "Ar-Rum", "Luqman", "As-Sajdah", "Al-Ahzab"],
    22: ["Al-Ahzab", "Saba", "Fatir", "Ya-Sin"],
    23: ["Ya-Sin", "As-Saffat", "Sad", "Az-Zumar"],
    24: ["Az-Zumar", "Ghafir", "Fussilat"],
    25: ["Fussilat", "Ash-Shura", "Az-Zukhruf", "Ad-Dukhan", "Al-Jathiyah"],
    26: ["Al-Ahqaf", "Muhammad", "Al-Fath", "Al-Hujurat", "Qaf", "Adh-Dhariyat"],
    27: ["Adh-Dhariyat", "At-Tur", "An-Najm", "Al-Qamar", "Ar-Rahman", "Al-Waqi'ah", "Al-Hadid"],
    28: ["Al-Mujadila", "Al-Hashr", "Al-Mumtahanah", "As-Saf", "Al-Jumu'ah", "Al-Munafiqun", "At-Taghabun", "At-Talaq", "At-Tahrim"],
    29: ["Al-Mulk", "Al-Qalam", "Al-Haqqah", "Al-Ma'arij", "Nuh", "Al-Jinn", "Al-Muzzammil", "Al-Muddaththir", "Al-Qiyamah", "Al-Insan", "Al-Mursalat"],
    30: ["An-Naba", "An-Nazi'at", "Abasa", "At-Takwir", "Al-Infitar", "Al-Mutaffifin", "Al-Inshiqaq", "Al-Buruj", "At-Tariq", "Al-A'la", "Al-Ghashiyah", "Al-Fajr", "Al-Balad", "Ash-Shams", "Al-Layl", "Ad-Duha", "Ash-Sharh", "At-Tin", "Al-Alaq", "Al-Qadr", "Al-Bayyinah", "Az-Zalzalah", "Al-Adiyat", "Al-Qari'ah", "At-Takathur", "Al-Asr", "Al-Humazah", "Al-Fil", "Quraysh", "Al-Ma'un", "Al-Kawthar", "Al-Kafirun", "An-Nasr", "Al-Masad", "Al-Ikhlas", "Al-Falaq", "An-Nas"],
}

SURAH_AYAHS = {
    "Al-Fatihah": 7,    "Al-Baqarah": 286,  "Al-Imran": 200,    "An-Nisa": 176,
    "Al-Ma'idah": 120,  "Al-An'am": 165,    "Al-A'raf": 206,    "Al-Anfal": 75,
    "At-Tawbah": 129,   "Yunus": 109,       "Hud": 123,         "Yusuf": 111,
    "Ar-Ra'd": 43,      "Ibrahim": 52,      "Al-Hijr": 99,      "An-Nahl": 128,
    "Al-Isra": 111,     "Al-Kahf": 110,     "Maryam": 98,       "Ta-Ha": 135,
    "Al-Anbiya": 112,   "Al-Hajj": 78,      "Al-Mu'minun": 118, "An-Nur": 64,
    "Al-Furqan": 77,    "Ash-Shu'ara": 227, "An-Naml": 93,      "Al-Qasas": 88,
    "Al-Ankabut": 69,   "Ar-Rum": 60,       "Luqman": 34,       "As-Sajdah": 30,
    "Al-Ahzab": 73,     "Saba": 54,         "Fatir": 45,        "Ya-Sin": 83,
    "As-Saffat": 182,   "Sad": 88,          "Az-Zumar": 75,     "Ghafir": 85,
    "Fussilat": 54,     "Ash-Shura": 53,    "Az-Zukhruf": 89,   "Ad-Dukhan": 59,
    "Al-Jathiyah": 37,  "Al-Ahqaf": 35,     "Muhammad": 38,     "Al-Fath": 29,
    "Al-Hujurat": 18,   "Qaf": 45,          "Adh-Dhariyat": 60, "At-Tur": 49,
    "An-Najm": 62,      "Al-Qamar": 55,     "Ar-Rahman": 78,    "Al-Waqi'ah": 96,
    "Al-Hadid": 29,     "Al-Mujadila": 22,  "Al-Hashr": 24,     "Al-Mumtahanah": 13,
    "As-Saf": 14,       "Al-Jumu'ah": 11,   "Al-Munafiqun": 11, "At-Taghabun": 18,
    "At-Talaq": 12,     "At-Tahrim": 12,    "Al-Mulk": 30,      "Al-Qalam": 52,
    "Al-Haqqah": 52,    "Al-Ma'arij": 44,   "Nuh": 28,          "Al-Jinn": 28,
    "Al-Muzzammil": 20, "Al-Muddaththir": 56, "Al-Qiyamah": 40, "Al-Insan": 31,
    "Al-Mursalat": 50,  "An-Naba": 40,      "An-Nazi'at": 46,   "Abasa": 42,
    "At-Takwir": 29,    "Al-Infitar": 19,   "Al-Mutaffifin": 36,"Al-Inshiqaq": 25,
    "Al-Buruj": 22,     "At-Tariq": 17,     "Al-A'la": 19,      "Al-Ghashiyah": 26,
    "Al-Fajr": 30,      "Al-Balad": 20,     "Ash-Shams": 15,    "Al-Layl": 21,
    "Ad-Duha": 11,      "Ash-Sharh": 8,     "At-Tin": 8,        "Al-Alaq": 19,
    "Al-Qadr": 5,       "Al-Bayyinah": 8,   "Az-Zalzalah": 8,   "Al-Adiyat": 11,
    "Al-Qari'ah": 11,   "At-Takathur": 8,   "Al-Asr": 3,        "Al-Humazah": 9,
    "Al-Fil": 5,        "Quraysh": 4,       "Al-Ma'un": 7,      "Al-Kawthar": 3,
    "Al-Kafirun": 6,    "An-Nasr": 3,       "Al-Masad": 5,      "Al-Ikhlas": 4,
    "Al-Falaq": 5,      "An-Nas": 6,
}
